version: "3"

services:
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Elixir Version, based on hexpm debian images:
        # ${ELIXIR_VER}-erlang-${OTP_VER}-${OS_NAME}-${OS_VER}, ...
        SOURCE: "hexpm/elixir"
        VARIANT: "1.11.4-erlang-23.2.7.2-debian-buster-20210326"
        # Or based on elixir official images
        # 1.11.4, 1.11, latest...
        # SOURCE: "elixir"
        # VARIANT: "latest"
        # Phoenix Version: 1.4.17, 1.5.4, ...
        PHOENIX_VERSION: "1.5.8"
        # Node Version: 12, 10, ...
        NODE_VERSION: "14"
    volumes:
      - /path/to/app_name:/app_name:cached
    # Runs app on the same network as the database container,
    # allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  postgres-data:
